In [1]:
# encoding numerical features to categorical data 
#type discretization and binarization
#Disretization(binning) :  process to transform continuous variable into discrete variable by creating a set of contiguous intervals that span the range of the variables values.
# why use it: 1. to reduce the effect of outliers by grouping them into bins
            # 2. to capture non-linear relationships between the feature and the target variable by creating bins

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived']  )

In [5]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
df.dropna(inplace=True)

In [7]:
df.shape

(714, 3)

In [9]:
x = df.iloc[:,1:]
y = df.iloc[:,0]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [ ]:
x_train.head()

      Age     Fare
328  31.0  20.5250
73   26.0  14.4542
253  30.0  16.1000
719  33.0   7.7750
666  25.0  13.0000

In [10]:
kbinAge = KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='uniform')
kbinFare = KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='quantile')

In [12]:
trf = ColumnTransformer([
    ('binAge',kbinAge,[0]),
    ('binFare',kbinFare,[1])
])

In [13]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [16]:
trf.named_transformers_['binAge'].n_bins_

array([5])

In [17]:
trf.named_transformers_['binAge'].bin_edges_

array([array([ 0.42 , 16.336, 32.252, 48.168, 64.084, 80.   ])],
      dtype=object)