In [1]:
# binarization: converting a numerical variable into a binary variable based on a threshold value.
# binning: converting a numerical variable into a categorical variable by grouping the values into bins or

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv("train.csv",usecols=["Age","Fare","SibSp","Parch","Survived"])

In [5]:
df.dropna(inplace=True)

In [6]:
df["family"] = df["SibSp"] + df["Parch"]

In [7]:
df.drop(["SibSp","Parch"],axis=1,inplace=True)

In [8]:
df.head()

   Survived   Age     Fare  family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [9]:
x = df[["Age","Fare","family"]]
y = df['Survived']

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x

In [14]:
x_train.head()

      Age     Fare  family
387  36.0  13.0000       0
685  25.0  41.5792       3
20   35.0  26.0000       0
331  45.5  28.5000       0
396  31.0   7.8542       0

In [11]:
from sklearn.preprocessing import Binarizer

In [21]:
trf = ColumnTransformer([
    ("binarization", Binarizer(copy=False), ["family"]),
], remainder="passthrough")

In [22]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)