In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')

In [4]:
df.sample(5)

    Cabin     Ticket number  Survived
330   NaN     367226      5         1
844   NaN     315090      4         0
132   NaN  A/5. 3337      2         0
813   NaN     347082      A         0
342   NaN     248740      A         0

In [8]:
df['number'].value_counts()

number
A    139
6    131
1    129
2    126
4    126
5    123
3    117
Name: count, dtype: int64

In [10]:
#extract the numerical part
df['number_numerical'] = pd.to_numeric(df['number'], errors='coerce',downcast='integer')
#extract categorical part
df['number_categorical'] = np.where(df['number_numerical'].isna(), df['number'], np.nan)

In [11]:
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical
0,NaN,A/5 21171,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,NaN,373450,A,0,NaN,A

In [12]:
df['cabin_num'] = df['Cabin'].str.extract('(\d+)') # capture numerical part
df['cabin_cat'] = df['Cabin'].str.extract('([A-Za-z]+)') # capture categorical part

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\parth\AppData\Local\Temp\ipykernel_23520\3918268575.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['cabin_num'] = df['Cabin'].str.extract('(\d+)') # capture numerical part

In [13]:
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN