In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
knn = KNNImputer(n_neighbors=3)  #weight can also be used to give more importance to closer neighbors
x_train_knn = knn.fit_transform(x_train)
x_test_knn = knn.transform(x_test)

In [12]:
pd.DataFrame(x_train_knn, columns = x_train.columns)

      Age  Pclass      Fare
0    45.5     1.0   28.5000
1    23.0     2.0   13.0000
2    32.0     3.0    7.9250
3    26.0     3.0    7.8542
4     6.0     3.0   31.2750
..    ...     ...       ...
707  21.0     3.0    7.6500
708  37.0     1.0   31.0000
709  41.0     3.0   14.1083
710  14.0     1.0  120.0000
711  21.0     1.0   77.2875

[712 rows x 3 columns]